### PR TITLE
Gometalinter fixes and gofmt

### LINKED ISSUE #47: Gometalinter issues
`Gometalinter` recommended many fixes, but I want to fix a few low hanging fruit issues.

### PR DESCRIPTION
**Pull request by vaskoz**
Just a few small fixes noticed by `gometalinter`.

This PR resolves #47

### CODE REVIEW

File: solr_test.go [hunk 1]
```diff
@@ -17,8 +17,7 @@ var _ = Describe("Solr Client", func() {
 	solrClient = solr.NewSolrZK("zk:2181", "solr", "solrtest")
 	locator = solrClient.GetSolrLocator()
 
-	var err error
-	err = solrClient.Listen()
+	var err error = solrClient.Listen()
```
Comment (extemporalgenome) [inline solr_test.go]: Why not make this `err := solrClient.Listen()` ? Is Listen returning a concrete error type?
